export const LOAD_TASKS_REQUEST_SUCCESS = 'LOAD_TASKS_REQUEST_SUCCESS';
export const LOAD_TASKS_REQUEST_ERROR = 'LOAD_TASKS_REQUEST_ERROR';

export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';

export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_ERROR = 'EDIT_TASK_ERROR';
